theme: jekyll-theme-slate
title: Ben Sand
description: York University, Department of Economics.
show_downloads: false
google_analytics:
# Site menu settings
menu:
  - title: "Blog"
    url: "/blog"
  - title: "Documentation"
    url: "/documentation"
  - title: "Support"
    url: "/support"
# End
